[package]
name = "cliphistory"
version = "0.1.0"
edition = "2024"

[dependencies]
sled = "0.34"
arboard = "3.4"
iced = { version = "0.12", features = ["tokio"] }
tokio = { version = "1.38", features = ["rt", "time", "sync"] } # Add "sync" here